apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: NodePort
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
  - name: "80"
    port: 80
    nodePort: 31704
    targetPort: 80
    protocol: TCP
  selector:
    io.kompose.service: app
  type: NodePort