FROM node

WORKDIR /usr/src/app

COPY package.json /usr/src/app

COPY package-lock.json /usr/src/app

RUN npm install pm2 -g

RUN npm install

COPY . /usr/src/app

EXPOSE 80

CMD ["pm2-docker", "start", "process.json"]